//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirCotizador.Central {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Central.BancoCentralSoap")]
    public interface BancoCentralSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizcion", ReplyAction="*")]
        ConsumirCotizador.Central.ObtenerCotizcionResponse ObtenerCotizcion(ConsumirCotizador.Central.ObtenerCotizcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizcion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirCotizador.Central.ObtenerCotizcionResponse> ObtenerCotizcionAsync(ConsumirCotizador.Central.ObtenerCotizcionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizcion", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirCotizador.Central.ObtenerCotizcionRequestBody Body;
        
        public ObtenerCotizcionRequest() {
        }
        
        public ObtenerCotizcionRequest(ConsumirCotizador.Central.ObtenerCotizcionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizcionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public ObtenerCotizcionRequestBody() {
        }
        
        public ObtenerCotizcionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizcionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirCotizador.Central.ObtenerCotizcionResponseBody Body;
        
        public ObtenerCotizcionResponse() {
        }
        
        public ObtenerCotizcionResponse(ConsumirCotizador.Central.ObtenerCotizcionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizcionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ObtenerCotizcionResult;
        
        public ObtenerCotizcionResponseBody() {
        }
        
        public ObtenerCotizcionResponseBody(double ObtenerCotizcionResult) {
            this.ObtenerCotizcionResult = ObtenerCotizcionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoCentralSoapChannel : ConsumirCotizador.Central.BancoCentralSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoCentralSoapClient : System.ServiceModel.ClientBase<ConsumirCotizador.Central.BancoCentralSoap>, ConsumirCotizador.Central.BancoCentralSoap {
        
        public BancoCentralSoapClient() {
        }
        
        public BancoCentralSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoCentralSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoCentralSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoCentralSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirCotizador.Central.ObtenerCotizcionResponse ConsumirCotizador.Central.BancoCentralSoap.ObtenerCotizcion(ConsumirCotizador.Central.ObtenerCotizcionRequest request) {
            return base.Channel.ObtenerCotizcion(request);
        }
        
        public double ObtenerCotizcion(string fecha) {
            ConsumirCotizador.Central.ObtenerCotizcionRequest inValue = new ConsumirCotizador.Central.ObtenerCotizcionRequest();
            inValue.Body = new ConsumirCotizador.Central.ObtenerCotizcionRequestBody();
            inValue.Body.fecha = fecha;
            ConsumirCotizador.Central.ObtenerCotizcionResponse retVal = ((ConsumirCotizador.Central.BancoCentralSoap)(this)).ObtenerCotizcion(inValue);
            return retVal.Body.ObtenerCotizcionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirCotizador.Central.ObtenerCotizcionResponse> ConsumirCotizador.Central.BancoCentralSoap.ObtenerCotizcionAsync(ConsumirCotizador.Central.ObtenerCotizcionRequest request) {
            return base.Channel.ObtenerCotizcionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirCotizador.Central.ObtenerCotizcionResponse> ObtenerCotizcionAsync(string fecha) {
            ConsumirCotizador.Central.ObtenerCotizcionRequest inValue = new ConsumirCotizador.Central.ObtenerCotizcionRequest();
            inValue.Body = new ConsumirCotizador.Central.ObtenerCotizcionRequestBody();
            inValue.Body.fecha = fecha;
            return ((ConsumirCotizador.Central.BancoCentralSoap)(this)).ObtenerCotizcionAsync(inValue);
        }
    }
}
